### PR TITLE
Convert data to JSON-LD

### LINKED ISSUE #70: Convert the Data to JSON

### LINKED ISSUE #72: JSON-LD context mapping

### PR DESCRIPTION
**Pull request by michael-sevcik**
The data are converted from RDF/XML and valid against the JSON Schema from #68 

TODO:
- [x] Validate the data using [Apache Jena](https://jena.apache.org/documentation/io/) riot command and tranfrom it to RDF.
- [ ] Consider using references to avoid duplicities
- [ ] Consider not defining the middleNames in the JSON-LD context

Resolves #70 

Resolves #72

### CODE REVIEW

**Comment by michael-sevcik** [comment]
@patinoboh @ori-no @rastoboh 

Don't you happen to know how to use reference in the mayor and townHall property to the objects defined in occupants and houses respectively in a way it would be valid against the JSON Schema from #68 ?

Also I can't firgure out how to properly define middleNames in the `@context` property, in RDF we use langstring type to avoid using arrays (as Klimek advised us), but in the XML and JSON it is used as array. I had a look at the solution from Vlado and they didn't define the array property in the context at all despite the fact that they have it in their domain model.

**Comment by patinoboh** [comment]
WOW! Great job. I have no idea how it works, but I'll have a look at it.
I only noticed the indentation in _jena.tts_.

**Comment by patinoboh** [comment]
- Looks like the _json data_ in .`jsonld ` are just generated from xml, am I right?
We couldn't figure out how to use the refferences, so we just copied the think. I believe this will be the case for "json" as well.
- Is there a reason why you have to copy the same contex over and over?
@michael-sevcik

**Comment by michael-sevcik** [comment]
@patinoboh 
> * Looks like the _json data_ in .`jsonld ` are just generated from xml, am I right?

Yea, you are basically right. I tried to replicated best I could considering the requirements of JSON Schema

>   We couldn't figure out how to use the refferences, so we just copied it everywhere. I believe this will be the case for "json" as well.
> * Is there a reason why you have to copy the same contex over and over?
>   @michael-sevcik

The reason for copying the data is that I used [this](https://docs.google.com/presentation/d/1rDs6keom3XN5pw0kx-vSFFxVTd1mxUoGmugK3XMutzc/edit#slide=id.g122b63e07f0_2_0) example from practicals as an inspiration.
image

Only to later find out, that Apache Jena does not use predefined prefixes and instead uses full IRIs. However, in order to use normal we would have to define the context only once and that involves changing the Schema and queries.

> In Vlados solution, jena generated file used rdf prefixes. Is that a difficult change? Would also be easied to compare with original rdf.

Unfortunately Vlado has it defined in the same way and it also uses the definion style from the example above and when I run the apache jena riot command on it, it creates a file with the same issues as we.

**Pull request merged**
