### PR TITLE
Update model and JSON schema

### LINKED ISSUE #47: Convert the conceptual model to a hierarchical model
Create one or more hierarchical diagrams corresponding to the conceptual one, showing how your data will be structured into hierarchies. Each hierarchical diagram will use directed associations, showing the nesting relation, and will have a root class with no incoming associations. It might be necessary to split the data into multiple hierarchies to avoid some redundancies.

[Source](https://jakub.xn--klmek-0sa.com/nprg036-hw3#:~:text=For%20representation%20of,avoid%20some%20redundancies.)

### LINKED ISSUE #69: Create JSON Schema

### PR DESCRIPTION
**Pull request by michael-sevcik**
- Removes the second hierarchy and adds the townHall property to the first hierarchy.
- Updates the JSON schema to match the updated model and [examples](https://docs.google.com/presentation/d/1rDs6keom3XN5pw0kx-vSFFxVTd1mxUoGmugK3XMutzc/edit#slide=id.gd09a3f55ea_0_112) from practicals (style of definitions - `$defs`, definition of the `Towns` entity and naming - lowerCamelCase).

See commits for futher details.

Resolves #47

Resolves #69

### CODE REVIEW

**Comment by patinoboh** [comment]
1. [schema](806e78c77b2907dfdb3e712c1d848f4f3d0559ea) is great, I would have forgotten about it.
2. I did not study json schema deeply, I will have a look at it in an hour.

**Comment by patinoboh** [comment]
What is `"ref="#/definitions/person"`??
Do not see it anywhere @michael-sevcik

**Comment by michael-sevcik** [comment]
> #/definitions/person

Yea, that's an artifact from the previous version. It should be "$ref": "#/$defs/mayor" etc. I'm going to fix it right away.

**Comment by patinoboh** [comment]
I changed this branch (somehow, sorry).
I believe it might be ok

**Pull request merged**
